package com.neo.assistant

import android.Manifest
import android.app.Activity
import android.app.AlertDialog
import android.os.Bundle
import android.os.Handler
import android.os.Looper
import android.content.pm.PackageManager
import android.graphics.Color
import android.media.MediaPlayer
import android.widget.*
import org.json.JSONObject
import java.io.File
import java.util.concurrent.Executors

class MyVoiceActivity : Activity() {
    private val handler = Handler(Looper.getMainLooper())
    private val network = Executors.newSingleThreadExecutor()
    private var recorder: PcmVoiceRecorder? = null
    private var player: MediaPlayer? = null
    private var foreground = false
    private var busy = false
    private var jobId: String? = null
    private lateinit var status: TextView
    private lateinit var recordingStatus: TextView
    private lateinit var consent: CheckBox
    private val buttons = mutableListOf<Button>()
    private val reference by lazy { File(filesDir, "my-voice-reference.wav") }
    private val generated by lazy { File(cacheDir, "my-voice-preview.wav") }
    private val clock = object : Runnable {
        override fun run() {
            val current = recorder ?: return
            recordingStatus.text = "Recording: ${current.seconds} / 20 seconds. Speak normally."
            handler.postDelayed(this, 250)
        }
    }
    private val poll = Runnable { refresh() }
    override fun onCreate(state: Bundle?) {
        super.onCreate(state)
        val layout = LinearLayout(this).apply {
            orientation = LinearLayout.VERTICAL; setPadding(28, 32, 28, 32); setBackgroundColor(Color.rgb(246, 249, 245))
        }
        setContentView(ScrollView(this).apply { addView(layout) })
        fun label(value: String, size: Float = 16f) = TextView(this).apply {
            text = value; textSize = size; setTextColor(Color.rgb(28, 55, 48)); setPadding(0, 14, 0, 14); layout.addView(this)
        }
        fun button(value: String, action: () -> Unit) = Button(this).apply {
            text = value; layout.addView(this); setOnClickListener { action() }; buttons.add(this)
        }
        button("Back") { finish() }
        label("My voice", 26f)
        label("1. Record 10?20 seconds", 21f)
        label("Use your normal voice in a quiet room, with no music or other speakers. Recording stops at 20 seconds. Leaving this screen cancels a recording in progress.")
        label("Read naturally: Hello, this is my normal speaking voice. I am recording a sample for my personal assistant. Please speak clearly and take your time. Today I am trying a new voice preview in Neo.")
        recordingStatus = label(if (reference.exists()) "A local voice sample is saved." else "No local recording yet.")
        consent = CheckBox(this).apply {
            text = "This is my own voice. I allow Neo to send this sample to my paired Python server to generate speech."
            layout.addView(this)
        }
        button("Record my voice") { beginRecording() }
        Button(this).apply { text = "Stop recording / playback"; layout.addView(this); setOnClickListener { recorder?.stop(); stopPlayback() } }
        button("Listen to my recording") { play(reference) }
        button("Delete phone recording") {
            stopPlayback(); reference.delete(); generated.delete(); recordingStatus.text = "Phone recording deleted. The server copy is separate."
        }
        label("2. Upload to Python", 21f)
        label("Only tapping Upload sends your recording. It stays in private storage on your phone and paired server until deleted. No paid voice API is used. This is voice enrollment, not call recording.")
        status = label("Pair with Python in Neo Home first.")
        button("Upload my voice") {
            if (!consent.isChecked) { status.text = "Confirm that this is your own voice first."; return@button }
            if (!reference.exists()) { status.text = "Record a sample first."; return@button }
            request({ api -> api.voiceRequest("PUT", "/v1/voice/reference", reference.readBytes(), "audio/wav", true) }) {
                status.text = "Voice sample saved on Python. You can now generate a preview."
            }
        }
        button("Check server / preview status") { refresh() }
        label("3. Generate and listen", 21f)
        label("Type a short English message. Neo adds an automated-assistant introduction. Similarity varies; it is not guaranteed to sound identical to you. Local generation may take minutes.")
        val message = EditText(this).apply {
            setText("This is a preview made with my owner's voice sample.")
            filters = arrayOf(android.text.InputFilter.LengthFilter(240)); layout.addView(this)
        }
        button("Generate in my voice") {
            if (message.text.isBlank()) { status.text = "Enter a short message."; return@button }
            val body = JSONObject().put("text", message.text.toString()).toString().toByteArray()
            request({ api -> api.voiceRequest("POST", "/v1/voice/preview", body) }) { response ->
                generated.delete()
                showJob(JSONObject(String(response)))
            }
        }
        button("Listen to generated preview") {
            val id = jobId
            if (id == null) { status.text = "Generate a preview or check server status first."; return@button }
            request({ api -> api.voiceRequest("GET", "/v1/voice/jobs/$id/audio") }) {
                generated.writeBytes(it)
                if (foreground) play(generated)
            }
        }
        button("Delete my voice from Python") {
            AlertDialog.Builder(this).setTitle("Delete server voice?").setMessage("Remove the voice reference and generated preview from your paired Python server? Your phone recording is separate.")
                .setNegativeButton("Cancel", null).setPositiveButton("Delete") { _, _ ->
                    request({ api -> api.voiceRequest("DELETE", "/v1/voice/reference") }) {
                        jobId = null; generated.delete(); status.text = "Server voice and preview deleted."
                    }
                }.show()
        }
        label("First-time server setup: run setup_voice.py in the Neo folder. It needs Python 3.11, model downloads and enough memory. Live SIM/WhatsApp caller audio is still not connected; this screen generates app previews only.")
    }
    private fun controls() { buttons.forEach { it.isEnabled = !busy && recorder == null } }
    private fun beginRecording() {
        stopPlayback()
        if (checkSelfPermission(Manifest.permission.RECORD_AUDIO) != PackageManager.PERMISSION_GRANTED) {
            requestPermissions(arrayOf(Manifest.permission.RECORD_AUDIO), 906); return
        }
        val current = PcmVoiceRecorder()
        recorder = current; controls(); handler.post(clock)
        current.record(reference) { error -> runOnUiThread {
            if (recorder === current) {
                recorder = null; handler.removeCallbacks(clock)
                if (!isDestroyed) { controls(); recordingStatus.text = error ?: "${current.seconds} seconds saved locally. Listen, then upload when ready." }
            }
        } }
    }
    override fun onRequestPermissionsResult(code: Int, permissions: Array<out String>, results: IntArray) {
        super.onRequestPermissionsResult(code, permissions, results)
        if (code == 906 && foreground) {
            if (results.firstOrNull() == PackageManager.PERMISSION_GRANTED) beginRecording()
            else recordingStatus.text = "Microphone access is needed to record. Allow it in Android app permissions when ready."
        }
    }
    private fun request(action: (ApiTransport) -> ByteArray, done: (ByteArray) -> Unit) {
        if (busy || recorder != null) return
        busy = true; controls(); status.text = "Connecting to Python?"
        network.execute {
            try {
                val connection = ConnectionStore(this)
                val result = action(ApiTransport(connection.url, connection.token(), BuildConfig.DEBUG))
                runOnUiThread { if (!isDestroyed) {
                    busy = false; controls()
                    try { done(result) } catch (_: Exception) { status.text = "Unexpected response or audio could not be saved. Check the paired server and retry." }
                } }
            } catch (error: Exception) {
                runOnUiThread { if (!isDestroyed) {
                    busy = false; controls()
                    status.text = when ((error as? ApiHttpException)?.status) {
                        401 -> "Pairing token rejected. Check your Python connection in Neo Home."
                        409 -> "A preview is running, not ready, or no server sample exists. Check status before retrying."
                        413, 415, 422 -> "Sample rejected. Record 10?20 seconds of clear speech, avoiding silence and distortion, then upload again."
                        503 -> "Voice engine is not installed. Run setup_voice.py on the Python server first."
                        404 -> "Voice API or preview unavailable. Restart the updated Python server and check status."
                        else -> "Could not complete the request. Check pairing, Python and USB forwarding; then check status before retrying."
                    }
                } }
            }
        }
    }
    private fun showJob(job: JSONObject) {
        jobId = job.getString("id")
        status.text = job.optString("message")
        if (job.optString("state") == "generating" && foreground) handler.postDelayed(poll, 2000)
    }
    private fun refresh() {
        handler.removeCallbacks(poll)
        request({ it.voiceRequest("GET", "/v1/voice") }) {
            val result = JSONObject(String(it))
            val job = result.optJSONObject("job")
            if (job != null) showJob(job)
            else {
                jobId = null
                status.text = (if (result.optBoolean("reference_saved")) "Voice sample saved on server. " else "No server voice sample. ") +
                    (if (result.optBoolean("engine_configured")) "Engine environment found; generate a preview to check model readiness." else "Voice engine setup required: run setup_voice.py on the server.")
            }
        }
    }
    private fun play(file: File) {
        stopPlayback()
        if (!file.isFile) { status.text = "No audio saved yet."; return }
        try {
            player = MediaPlayer().apply {
                setDataSource(file.absolutePath)
                setOnCompletionListener { stopPlayback() }
                setOnErrorListener { _, _, _ -> stopPlayback(); status.text = "Audio could not be played."; true }
                prepare(); start()
            }
        } catch (_: Exception) { stopPlayback(); status.text = "Audio could not be played." }
    }
    private fun stopPlayback() { player?.release(); player = null }
    override fun onResume() { super.onResume(); foreground = true }
    override fun onPause() {
        foreground = false; recorder?.stop(true); stopPlayback(); handler.removeCallbacks(clock); handler.removeCallbacks(poll)
        super.onPause()
    }
    override fun onDestroy() { recorder?.stop(true); network.shutdown(); handler.removeCallbacksAndMessages(null); super.onDestroy() }
}
